name: Publish NuGet package

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
        PROJECT_FILE_PATH: ./src/Strings.Abbreviations/Strings.Abbreviations.csproj
        # Official NuGet Feed settings
        NUGET_FEED: https://api.nuget.org/v3/index.json
        NUGET_KEY: ${{ secrets.NUGET_KEY }}

    steps:
      - uses: actions/checkout@v2
      - name: Get project version
        id: projectVersion
        run: |
          $versionJsonOutput=dotnet version -f ${{ env.PROJECT_FILE_PATH }} --output-format=json
          $value=$versionJsonOutput | jq -r '.currentVersion'
          echo ::set-output name=PROJECT_VERSION::'$value'

      - name: Publish NuGet on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: ${{ env.PROJECT_FILE_PATH }}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          TAG_COMMIT: false